"""Updated Question Table

Revision ID: 829eef7078d6
Revises: f71403b1bd3a
Create Date: 2024-02-18 14:01:31.608195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '829eef7078d6'
down_revision: Union[str, None] = 'f71403b1bd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

response_type_enum = sa.Enum('text', 'number', 'choice', name='response_type', create_type=False)
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    response_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('questions', sa.Column('response_type', response_type_enum, nullable=False, default='text'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'first_name')
    op.drop_column('questions', 'response_type')
    # ### end Alembic commands ###
